### ISSUE TITLE
Make pwsh as default on windows if it install

### ISSUE THREAD

**Issue by AlonGvili** [daverickdunn/full-powershell#13]
https://github.com/daverickdunn/full-powershell/blob/ec70e493959fffa92e2deeaeb9538df076a48a46/src/index.ts#L114

in your current code, you test if it windows then run PowerShell 5.1
I would suggest checking if pwsh is installed on windows then using it

```js
        const regex = /\\PowerShell\\7/g;
        const isPwshInstalled = process.env.Path?.split(';').some((path: string) => path.match(regex));
        const exe = os.platform() === 'win32' && isPwshInstalled ? 'pwsh' : os.platform() === 'win32' ? 'powershell' : 'pwsh';
```

Those are the changes that I used in a clone to make it work.
I add them from lines 138-140 and removed line 114

BTW
 **thank you so much** for this, I use this lib to make some awesome apps

**Comment by daverickdunn** [comment]
Hi, apologies for not getting back sooner.

What you're suggesting is not a terrible idea, but I've decided not to implement it for two reasons:

1. You can already control which version you want to use by specifying the `exe_path` in the [options](https://github.com/daverickdunn/full-powershell#powershelloptions-object)
2. There are significant enough differences between PowerShell 5 and 7 that this would almost certainly introduce bugs for users who want to deploy to different environments. The most obvious of which is how Date Objects are parsed using ConvertTo-JSON, which is a core part of this library. i.e. ( `\/Date(1646397281311)\/` vs. `2022-03-04T12:35:37` )

I'm glad you like the library, please let me know if you have any other issues or suggestions.
