### ISSUE TITLE
Importing using CommonJS not functioning as documented

### ISSUE THREAD

**Issue by aquist09** [daverickdunn/full-powershell#15]
The readme shows the below line to import using CommonJS, but this will result in a 'TypeError: PowerShell is not a Constructor' error when you go to create an instance of PowerShell.
`const PowerShell = require('full-powershell');`

I was able to successfully import by specifying PowerShell on the require statement.
`const PowerShell = require('full-powershell').PowerShell;`

I would imagine the documentation needs updated or the PowerShell constructor needs to be surfaced so the CommonJS import works as documented.

**Comment by daverickdunn** [comment]
Thanks for pointing that out, I've updated the docs along with some bugfixes. [2.0.0](https://www.npmjs.com/package/full-powershell/v/2.0.0)
