### ISSUE TITLE
Warning is not returned for this command: Connect-AzAccount -UseDeviceAuthentication 

### ISSUE THREAD

**Issue by blueleader07** [daverickdunn/full-powershell#18]
Hi @daverickdunn hope you're doing well.

Been using this library for quite some time (as you may remember) and it's worked wonderfully.  I'm running into a bit of a wall with one particular command and wondering if you have any ideas.

The last line in the log is:
[>] invoking: Connect-AzAccount -UseDeviceAuthentication

... and then nothing.  

Just for the heck of it I tried the same command in **node-powershell** and got this printed in the log:
**WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code EA7LKRDG8 to authenticate.**

Any idea if it's possible to get that warning message?  Ultimately I'm trying to script something that opens the browser and logs in (automatically) using a combination of full-powershell and puppeteer.  If I can just get the warning message I think I can do it.  I was expecting the warning message to come from the warning$ stream ... but nothing comes through.

I did pull down your source code and tried to write my own unit test ... and saw the same behavior.  "Connect-AzAccount -UseDeviceAuthentication" hangs (no messages appear in the streams).

Here is the unit test.  If you have a moment would you mind running and seeing if you see the same behavior?

```
test('Connect-AzAccount', (done) => {
    let shell = new PowerShell();
    shell.success$.subscribe(
        (res) => {
            console.log('res', res)
            shell.destroy();
            done();
        }
    );
    shell.warning$.subscribe(
        (res) => {
            console.log('res', res)
            shell.destroy();
            done();
        }
    );
    shell.debug$.subscribe(
        (res) => {
            console.log('res', res)
            shell.destroy();
            done();
        }
    );
    shell.info$.subscribe(
        (res) => {
            console.log('res', res)
            shell.destroy();
            done();
        }
    );
    shell.verbose$.subscribe(
        (res) => {
            console.log('res', res)
            shell.destroy();
            done();
        }
    );
    shell.error$.subscribe(
        (res) => {
            console.log('res', res)
            shell.destroy();
            done();
        }
    );
    shell.call('Connect-AzAccount -UseDeviceAuthentication', null)
});
```

**Comment by blueleader07** [comment]
OK, I've gotten closer.   Seems like the warning message comes through in stream 3>$null.  I'm not sure why it doesn't emit an event in the $wv variable.  
```
try {
        Invoke-Command -NoNewScope -ScriptBlock {
            ${command}
        } 1>$null 2>$null 3>$null 4>$vv 5>$dv 6>$null -ov ov -ev ev -wv wv -iv iv
    } 
```

If I tweak so that 3> writes to a file ... I can see the warning message in the file!
```
try {
        Invoke-Command -NoNewScope -ScriptBlock {
            ${command}
        } 1>$null 2>$null 3>$wv 4>$vv 5>$dv 6>$null -ov ov -ev ev -iv iv
    } 
```
I might try (tomorrow) writing a custom "call" method that redirects to a file.  Maybe there's a way to redirect to a file and a variable (if that makes sense?) I'm not good enough with Powershell though.  

This is a ONE OFF.  So if I can create my own call method, which should be possible, there's no need for any code changes to your repo.  Will post back my results!

**Comment by blueleader07** [comment]
An update:
1. I was able to provide my own "wrap" function and get this working as I wanted!  Woohoo!
2. Then I discovered an easier way ... and don't need any of this anymore.  

It was still interesting to go through all this but sometimes at the end you discover a way that's 10x easier ... oh well!  
I will close this ticket.

**Comment by daverickdunn** [comment]
Hey, sorry, I was on holidays last week. I'm glad you got sorted, but that's still interesting nonetheless and I might try to fix it for posterity. Which PowerShell, OS, etc. were you using? Thanks.
