### ISSUE TITLE
Can run string script with embed in JavaScript Code ?

### ISSUE THREAD

**Issue by WingDust** [daverickdunn/full-powershell#7]
Such as I wirte a script 
like this
```powershell
Function Add
{
$sum=0
$args | foreach {$sum=$sum+$_}
$sum
}

Add 1 2 3 4 5 6 7 8 9 10
```
can run like this ?
```js
import { PowerShell } from 'full-powershell';
const ps = new Shell({
  executionPolicy: 'Bypass',
  noProfile: true
});
const command = 'Function Add
{
$sum=0
$args | foreach {$sum=$sum+$_}
$sum
}

Add 1 2 3 4 5 6 7 8 9 10'
ps.addCommand(command);
ps.invoke()
.then(output => {
  console.log(output);
})
.catch(err => {
  console.log(err);
});
```

**Comment by daverickdunn** [comment]
Hi, that's written for _Node-PowerShell_, which is similar, but not the same. Please check the [README](https://github.com/daverickdunn/full-powershell#readme) for instructions on how to use _Full-PowerShell_. If you're having a general issue writing your code, please try asking on StackOverflow.
