### ISSUE TITLE
Commands are Silently Failing

### ISSUE THREAD

**Issue by daverickdunn** [daverickdunn/full-powershell#8]
Commands are returning empty strings instead of expected output when run on AWS Lambda.

**Comment by daverickdunn** [comment]
Issue was caused by failing to create `.tmp` files in some environments. An option has been added to change the path when instantiating the class.
Commit: 872b6cf3d6ecac7ab4276765c69e65206ab477be
Release: [v1.4.0](https://www.npmjs.com/package/full-powershell/v/1.4.0)

**Comment by daverickdunn** [comment]
@blueleader07 - I'd be really grateful if you could test this on Lambda. See [PowerShellOptions](https://github.com/daverickdunn/full-powershell#powershelloptions-object) for more details.

**Comment by blueleader07** [comment]
It works!!!  You are amazing.  Tested locally and in Lambda.  I used your new options class like this: 
```
const ps = new PowerShell({
    tmp_dir: environmentUtils.isLocal() ? undefined : '/tmp/'
})
```

... and here is the log from Lambda:
```

INFO	connecting powershell ...
--
INFO	output {  success: [],  error: [],  warning: [],  verbose: [],  debug: [],  info: []}
INFO	output {  success: [],  error: [],  warning: [],  verbose: [],  debug: [],  info: []}
INFO	output {  success: [],  error: [],  warning: [],  verbose: [],  debug: [],  info: []}
INFO	output {  success: [],  error: [],  warning: [    'Your connection has been redirected to the following URI: "https://nam12b.ps.compliance.protection.outlook.com/powershell-liveid?PSVersion=7.1.3\u0000"\n'  ],  verbose: [],  debug: [],  info: []}
INFO	output {  success: [    '\n' +      'ModuleType Version    PreRelease Name                                ExportedCommands\n' +      '---------- -------    ---------- ----                                ----------------\n' +      'Script     1.0                   tmp_uz2dibhh.d5s                    {Add-ccComplianceCaseMember, Delete-ccQuarantineMe…\n' +      '\n'  ],  error: [],  warning: [],  verbose: [],  debug: [],  info: []}
INFO	ModuleType Version    PreRelease Name                                ExportedCommands---------- -------    ---------- ----                                ----------------Script     1.0                   tmp_uz2dibhh.d5s                    {Add-ccComplianceCaseMember, Delete-ccQuarantineMe…
INFO	output {  success: [],  error: [],  warning: [    'Your connection has been redirected to the following URI: "https://nam12b.ps.compliance.protection.outlook.com/powershell-liveid?PSVersion=7.1.3\u0000"\n'  ],  verbose: [],  debug: [],  info: []}
INFO	output {  success: [    '\n' +      'ModuleType Version    PreRelease Name                                ExportedCommands\n' +      '---------- -------    ---------- ----                                ----------------\n' +      'Script     1.0                   tmp_0vtez42j.g0i                    {Add-ComplianceCaseMember, Delete-QuarantineMessag…\n' +      '\n'  ],  error: [],  warning: [],  verbose: [],  debug: [],  info: []}
INFO	ModuleType Version    PreRelease Name                                ExportedCommands---------- -------    ---------- ----                                ----------------Script     1.0                   tmp_0vtez42j.g0i                    {Add-ComplianceCaseMember, Delete-QuarantineMessag…
INFO	connected in 00:00:35

```
I'll give it a nice stress test later today / tonight.  For now I was able to connect, run some commands and get results which is exactly what I needed (as was trying to do with node-powershell).  

I have the powershell layer in a private repo.  It's not difficult to do once you figure out "what" to do.  I'll throw together some documentation for you asap (probably tomorrow will be the first chance I get).

Thanks again!

**Comment by daverickdunn** [comment]
Awesome! Hopefully everything will behave going forward. I'll update some of the outputs in a v2 to make the API simpler, but won't have time this week. 

A look at your Lambda Layer steps would be amazing. I need to try recall exactly why the ECS / Lambda containers didn't work for me in the past, I do remember it wasn't actually the pwsh version itself but the .net version that wasn't high enough. I see 3.1 is available since last year, so if it's high enough for whatever it was I need to run, then I might be doing some refactoring/redeploying myself...

As an aside, a big issue I spent a good deal of time trying to figure out is how to start/stop remote sessions quickly. Exchange only allows you to create up to 3 sessions within a certain timeframe (~15 minutes). This makes running lambdas in quick succession a problem. There are supposed to be ways to cleanly disconnect and/or reconnect to a session, but I could not make this happen for love nor money, so I had to keep processes alive for at least a few minutes to handle 'bursts' of activity without getting locked out. Your usage pattern may be different, so it might not be a problem, but if you're thinking of running lots of commands against the same tenant, in quick succession, you should test this first as it might be a big issue for you. That _might_ have just been an EXO problem, and it _might_ no longer exist in EXO V2, I can't say for sure, but some things I've noticed have given me that indication.

**Comment by blueleader07** [comment]
@daverickdunn Here's my [writeup](https://medium.com/@sean.mckeon07/lambda-powershell-layer-15c0ec6f6d4a).  Hopefully you can read it.  I'm not sure if I can legally post source code or how that works (I can look into it).  But you'll at least have the steps I followed to get from A -> B.  You might not need the PSWSMan stuff like I did (ended up being a bit of a custom build).  

As far as my use case -- I'm working around the 3 session limit by processing things in batches with a throttle in front.  I'm using step functions and I have some logic that prevents two of the same state machines from running at the same time.  You could achieve similar results with an SQS queue infront of Lambda.  User actions will write to a database table ... and then periodically (once a day ... twice ... three times ... we aren't sure yet) lambda will read from that table and execute powershell commands.  When this happens lambda will open a powershell session ... run a bunch of commands ... and close the session (using your destroy() method).  I'm breaking the list of powershell commands into chunks of 300 and running them as separate lambdas until complete (to avoid the 15 minute runtime limit of Lambda).  

The session limit kills the scalability of serverless, but I do like our potential for cost savings.  We're only planning to run our Powershell lambdas a few times a day (max) so there's no need to pay for a server to run 24x7.  We were sort of forced to use Powershell given our budget and it's significantly cheaper than quote the Microsoft gave us for the alternative (Graph API).  As of right now ... it's full steam ahead with Powershell.  Maybe in the future, if things change, we'll switch to Graph API.   

Very cool that your library worked for us and I definitely appreciate the time you put in.  Let me know if you have any trouble in lambda / layer land I'm happy to provide more info.

**Comment by daverickdunn** [comment]
Cool, thanks a mill., the writeup is very useful. I'm gonna have a dig around a figure out if I can use all my commands on pwsh 7 and .net core 3.1. It looks like they've added all the missing modules back in. Could be moving over to Fargate in a few weeks if that's the case.
